import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { AgentConfig, HookFormat } from './agents';

export type AgentHookEvent = 'PreToolUse' | 'PostToolUse' | 'SessionStart' | 'SessionEnd' | 'Stop';

export interface HookEntry {
  event: AgentHookEvent;
  matcher: string;
  command: string;
  timeout?: number;
}

export interface AgentHookConfigFile {
  path: string;
  format: HookFormat;
  raw: unknown;
}

export interface HookWriterResult {
  agent: string;
  status: 'configured' | 'skipped' | 'unsupported' | 'error';
  configPath?: string;
  backupPath?: string;
  error?: Error;
}

export interface AgentHookConfigWriter {
  readonly agentId: string;
  isApplicable(): boolean;
  readConfig(): AgentHookConfigFile | undefined;
  writeConfig(config: AgentHookConfigFile): void;
  buildDefaultConfig(hooks: HookEntry[]): AgentHookConfigFile;
  syncHooks(config: AgentHookConfigFile, hooks: HookEntry[]): AgentHookConfigFile;
}

function backupPathFor(configPath: string): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  return `${configPath}.crewloop-backup-${timestamp}`;
}

function agentIsInstalled(agent: AgentConfig): boolean {
  return (
    fs.existsSync(agent.skillsDir) ||
    Boolean(
      agent.hooks.supported && agent.hooks.configPath && fs.existsSync(path.dirname(agent.hooks.configPath))
    )
  );
}

function configsEqual(a: AgentHookConfigFile, b: AgentHookConfigFile): boolean {
  if (a.format === 'json' && b.format === 'json') {
    return JSON.stringify(a.raw) === JSON.stringify(b.raw);
  }
  return String(a.raw) === String(b.raw);
}

function isCrewLoopCommand(command: string): boolean {
  return command.includes('crewloop-shim');
}

interface ParsedKimiBlock {
  rawLines: string[];
  event?: string;
  matcher?: string;
  command?: string;
  timeout?: number;
  isCrewLoop: boolean;
}

/**
 * Minimal TOML writer for Kimi Code's [[hooks]] array-of-tables.
 * Preserves comments and other tables outside the [[hooks]] section.
 * Removes legacy [hooks] tables that were generated by older CrewLoop versions.
 */
class KimiHookWriter implements AgentHookConfigWriter {
  readonly agentId = 'kimi';

  constructor(private agent: AgentConfig) {}

  isApplicable(): boolean {
    return agentIsInstalled(this.agent);
  }

  readConfig(): AgentHookConfigFile | undefined {
    const configPath = this.agent.hooks.configPath;
    if (!fs.existsSync(configPath)) {
      return undefined;
    }
    return {
      path: configPath,
      format: 'toml',
      raw: fs.readFileSync(configPath, 'utf8'),
    };
  }

  writeConfig(config: AgentHookConfigFile): void {
    fs.mkdirSync(path.dirname(config.path), { recursive: true });
    fs.writeFileSync(config.path, String(config.raw), 'utf8');
  }

  buildDefaultConfig(hooks: HookEntry[]): AgentHookConfigFile {
    return {
      path: this.agent.hooks.configPath,
      format: 'toml',
      raw: this.serializeHooks(hooks),
    };
  }

  syncHooks(config: AgentHookConfigFile, hooks: HookEntry[]): AgentHookConfigFile {
    const content = this.removeLegacyHooksTable(String(config.raw));
    const { otherSegments, blocks } = this.parseBlocks(content);

    const segments: string[] = [];
    if (otherSegments[0].length > 0) segments.push(otherSegments[0]);
    for (let i = 0; i < blocks.length; i++) {
      if (!blocks[i].isCrewLoop) {
        segments.push(this.serializeBlock(blocks[i].rawLines));
      }
      if (otherSegments[i + 1].length > 0) segments.push(otherSegments[i + 1]);
    }
    for (const hook of hooks) {
      segments.push(this.serializeBlock(this.toKimiBlock(hook).rawLines));
    }

    return { ...config, raw: segments.join('\n') };
  }

  private toKimiBlock(hook: HookEntry): ParsedKimiBlock {
    // Kimi Code compiles `matcher` as a JavaScript RegExp. A bare `*` is invalid,
    // so the CrewLoop wildcard `*` must be emitted as `.*` for Kimi.
    const matcher = hook.matcher === '*' ? '.*' : hook.matcher;
    const lines: string[] = ['[[hooks]]'];
    lines.push(`event = "${hook.event}"`);
    lines.push(`matcher = "${matcher}"`);
    lines.push(`command = "${hook.command}"`);
    if (hook.timeout !== undefined) {
      lines.push(`timeout = ${hook.timeout}`);
    }
    return {
      rawLines: lines,
      event: hook.event,
      matcher,
      command: hook.command,
      timeout: hook.timeout,
      isCrewLoop: true,
    };
  }

  private serializeHooks(hooks: HookEntry[]): string {
    return hooks.map((hook) => this.serializeBlock(this.toKimiBlock(hook).rawLines)).join('\n');
  }

  private serializeBlock(lines: string[]): string {
    return lines.join('\n');
  }

  private parseBlock(rawLines: string[]): ParsedKimiBlock {
    const block: ParsedKimiBlock = { rawLines, isCrewLoop: false };
    for (const line of rawLines) {
      const trimmed = line.trim();
      const kv = /^([a-zA-Z0-9_]+)\s*=\s*"(.*)"$/.exec(trimmed);
      if (kv) {
        const key = kv[1];
        const value = kv[2];
        if (key === 'event') block.event = value;
        if (key === 'matcher') block.matcher = value;
        if (key === 'command') block.command = value;
      }
      const numKv = /^([a-zA-Z0-9_]+)\s*=\s*(\d+)$/.exec(trimmed);
      if (numKv && numKv[1] === 'timeout') {
        block.timeout = parseInt(numKv[2], 10);
      }
    }
    if (block.command && isCrewLoopCommand(block.command)) {
      block.isCrewLoop = true;
    }
    return block;
  }

  private parseBlocks(content: string): { otherSegments: string[]; blocks: ParsedKimiBlock[] } {
    const lines = content.split('\n');
    const otherSegments: string[] = [];
    const blocks: ParsedKimiBlock[] = [];

    let currentOther: string[] = [];
    let currentBlock: string[] | null = null;

    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed === '[[hooks]]') {
        otherSegments.push(currentOther.join('\n'));
        currentOther = [];
        if (currentBlock) {
          blocks.push(this.parseBlock(currentBlock));
        }
        currentBlock = [line];
        continue;
      }

      if (currentBlock) {
        if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
          blocks.push(this.parseBlock(currentBlock));
          currentBlock = null;
          currentOther.push(line);
        } else {
          currentBlock.push(line);
        }
      } else {
        currentOther.push(line);
      }
    }

    if (currentBlock) {
      blocks.push(this.parseBlock(currentBlock));
    }
    otherSegments.push(currentOther.join('\n'));

    return { otherSegments, blocks };
  }

  private removeLegacyHooksTable(content: string): string {
    const lines = content.split('\n');
    const result: string[] = [];
    let i = 0;

    while (i < lines.length) {
      const trimmed = lines[i].trim();

      if (trimmed === '[hooks]') {
        const tableLines: string[] = [lines[i]];
        let j = i + 1;
        let hasCrewLoopCommand = false;

        while (j < lines.length) {
          const t = lines[j].trim();
          if (t.startsWith('[') && t.endsWith(']')) break;
          tableLines.push(lines[j]);
          const keyValue = /^[a-zA-Z0-9_]+\s*=\s*"(.*)"$/.exec(t);
          if (keyValue && isCrewLoopCommand(keyValue[1])) {
            hasCrewLoopCommand = true;
          }
          j++;
        }

        if (!hasCrewLoopCommand) {
          result.push(...tableLines);
        }

        i = j;
        continue;
      }

      result.push(lines[i]);
      i++;
    }

    return result.join('\n');
  }
}

interface JsonHookCommand {
  type: 'command';
  command: string;
  timeout?: number;
  statusMessage?: string;
}

interface JsonMatcherBlock {
  matcher: string;
  hooks: JsonHookCommand[];
}

function isCrewLoopMatcherBlock(block: JsonMatcherBlock): boolean {
  if (!Array.isArray(block.hooks) || block.hooks.length === 0) return false;
  return block.hooks.every(
    (h) => typeof h.command === 'string' && isCrewLoopCommand(h.command)
  );
}

abstract class GroupedJsonHookWriter implements AgentHookConfigWriter {
  abstract readonly agentId: string;
  abstract readonly rootKey: string;
  abstract readonly legacyRootKey: string;

  constructor(private agent: AgentConfig) {}

  isApplicable(): boolean {
    return agentIsInstalled(this.agent);
  }

  readConfig(): AgentHookConfigFile | undefined {
    const configPath = this.agent.hooks.configPath;
    if (!fs.existsSync(configPath)) {
      return undefined;
    }
    try {
      const raw = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      return { path: configPath, format: 'json', raw };
    } catch (cause) {
      throw new Error(
        `Malformed JSON config at ${configPath}: ${cause instanceof Error ? cause.message : String(cause)}`
      );
    }
  }

  writeConfig(config: AgentHookConfigFile): void {
    fs.mkdirSync(path.dirname(config.path), { recursive: true });
    fs.writeFileSync(config.path, JSON.stringify(config.raw, null, 2) + '\n', 'utf8');
  }

  buildDefaultConfig(hooks: HookEntry[]): AgentHookConfigFile {
    const root = this.buildRoot(hooks);
    return {
      path: this.agent.hooks.configPath,
      format: 'json',
      raw: { [this.rootKey]: root },
    };
  }

  syncHooks(config: AgentHookConfigFile, hooks: HookEntry[]): AgentHookConfigFile {
    const clone = JSON.parse(JSON.stringify(config.raw)) as Record<string, unknown>;

    if (clone[this.legacyRootKey] && typeof clone[this.legacyRootKey] === 'object') {
      this.cleanupLegacyKeys(clone[this.legacyRootKey] as Record<string, JsonMatcherBlock[] | string | object>);
      if (this.legacyRootKey !== this.rootKey) {
        const legacyRoot = clone[this.legacyRootKey] as Record<string, unknown>;
        if (Object.keys(legacyRoot).length === 0) {
          delete clone[this.legacyRootKey];
        }
      }
    }

    if (!clone[this.rootKey] || typeof clone[this.rootKey] !== 'object') {
      clone[this.rootKey] = {};
    }
    const root = clone[this.rootKey] as Record<string, JsonMatcherBlock[] | string | object>;

    for (const hook of hooks) {
      const eventArray = this.ensureEventArray(root, hook.event);
      const filtered = eventArray.filter((block) => !isCrewLoopMatcherBlock(block));
      filtered.push(this.toMatcherBlock(hook));
      root[hook.event] = filtered;
    }

    return { ...config, raw: clone };
  }

  private buildRoot(hooks: HookEntry[]): Record<string, JsonMatcherBlock[]> {
    const root: Record<string, JsonMatcherBlock[]> = {};
    for (const hook of hooks) {
      root[hook.event] = [this.toMatcherBlock(hook)];
    }
    return root;
  }

  private toMatcherBlock(hook: HookEntry): JsonMatcherBlock {
    const command: JsonHookCommand = { type: 'command', command: hook.command };
    if (hook.timeout !== undefined) {
      command.timeout = hook.timeout;
    }
    return { matcher: hook.matcher, hooks: [command] };
  }

  private ensureEventArray(
    root: Record<string, JsonMatcherBlock[] | string | object>,
    event: string
  ): JsonMatcherBlock[] {
    const existing = root[event];
    if (Array.isArray(existing)) {
      return existing as JsonMatcherBlock[];
    }
    const empty: JsonMatcherBlock[] = [];
    root[event] = empty;
    return empty;
  }

  private cleanupLegacyKeys(root: Record<string, JsonMatcherBlock[] | string | object>): void {
    for (const key of ['before_tool_use', 'after_tool_use']) {
      const value = root[key];
      if (typeof value === 'string' && isCrewLoopCommand(value)) {
        delete root[key];
        continue;
      }
      if (value && typeof value === 'object' && !Array.isArray(value)) {
        const obj = value as { command?: string; args?: string[] };
        const full = [obj.command || '', ...(obj.args || [])].join(' ').trim();
        if (full.includes('crewloop-shim')) {
          delete root[key];
        }
      }
    }
  }
}

class CodexHookWriter extends GroupedJsonHookWriter {
  readonly agentId = 'codex';
  readonly rootKey = 'hooks';
  readonly legacyRootKey = 'hooks';
}

class ClaudeHookWriter extends GroupedJsonHookWriter {
  readonly agentId = 'claude';
  readonly rootKey = 'hooks';
  readonly legacyRootKey = 'hooks';
}

class AgyHookWriter extends GroupedJsonHookWriter {
  readonly agentId = 'agy';
  readonly rootKey = 'crewloop';
  readonly legacyRootKey = 'hooks';
}

function cleanupLegacyAgyConfig(): void {
  const legacyPath = path.join(os.homedir(), '.agy', 'config.json');
  if (!fs.existsSync(legacyPath)) {
    return;
  }
  try {
    const raw = JSON.parse(fs.readFileSync(legacyPath, 'utf8')) as Record<string, unknown>;
    if (raw && typeof raw === 'object') {
      delete raw.crewloop;
      if (Object.keys(raw).length === 0) {
        fs.unlinkSync(legacyPath);
      } else {
        fs.writeFileSync(legacyPath, JSON.stringify(raw, null, 2) + '\n', 'utf8');
      }
    }
  } catch {
    // Ignore malformed legacy config.
  }
}

const CREWLOOP_PLUGIN_MARKER = '// CREWLOOP-PLUGIN v1';

function generateOpenCodePlugin(): string {
  return `// CREWLOOP-PLUGIN v1 — do not edit; regenerate with \`crewloop install\`
const { spawn } = require('node:child_process');

function sendEvent(payload) {
  try {
    const child = spawn('crewloop-shim', ['opencode'], {
      stdio: ['pipe', 'ignore', 'ignore'],
    });
    child.stdin.write(JSON.stringify(payload));
    child.stdin.end();
  } catch {
    // Never block opencode.
  }
}

export const CrewLoopPlugin = async () => {
  return {
    'tool.execute.before': async (input, output) => {
      sendEvent({
        tool: input.tool,
        event_type: 'tool_start',
        cwd: input.cwd,
      });
    },
    'tool.execute.after': async (input, output) => {
      sendEvent({
        tool: input.tool,
        event_type: 'tool_end',
        cwd: input.cwd,
        success: output?.success !== false,
        duration_ms: output?.duration,
      });
    },
  };
};
`;
}

class OpenCodePluginWriter implements AgentHookConfigWriter {
  readonly agentId = 'opencode';

  constructor(private agent: AgentConfig) {}

  isApplicable(): boolean {
    return agentIsInstalled(this.agent);
  }

  readConfig(): AgentHookConfigFile | undefined {
    const configPath = this.agent.hooks.configPath;
    if (!fs.existsSync(configPath)) {
      return undefined;
    }
    return {
      path: configPath,
      format: 'plugin',
      raw: fs.readFileSync(configPath, 'utf8'),
    };
  }

  writeConfig(config: AgentHookConfigFile): void {
    fs.mkdirSync(path.dirname(config.path), { recursive: true });
    fs.writeFileSync(config.path, String(config.raw), 'utf8');
  }

  buildDefaultConfig(hooks: HookEntry[]): AgentHookConfigFile {
    return {
      path: this.agent.hooks.configPath,
      format: 'plugin',
      raw: generateOpenCodePlugin(),
    };
  }

  syncHooks(config: AgentHookConfigFile, hooks: HookEntry[]): AgentHookConfigFile {
    const content = String(config.raw);
    const generated = generateOpenCodePlugin();

    // If the file already contains the CrewLoop marker and is identical, keep it.
    if (content.includes(CREWLOOP_PLUGIN_MARKER) && content === generated) {
      return config;
    }

    // If the file exists but has no CrewLoop marker, preserve it by backing up
    // and replacing with the CrewLoop plugin.
    return { ...config, raw: generated };
  }
}

function createWriter(agent: AgentConfig): AgentHookConfigWriter | undefined {
  if (!agent.hooks.supported) {
    return undefined;
  }
  switch (agent.id) {
    case 'kimi':
      return new KimiHookWriter(agent);
    case 'codex':
      return new CodexHookWriter(agent);
    case 'claude':
      return new ClaudeHookWriter(agent);
    case 'agy':
      return new AgyHookWriter(agent);
    case 'opencode':
      return new OpenCodePluginWriter(agent);
    default:
      return undefined;
  }
}

export function installHooksForAgent(
  agent: AgentConfig,
  options: { dryRun?: boolean; backup?: boolean } = {}
): HookWriterResult {
  if (!agent.hooks.supported) {
    return { agent: agent.id, status: 'unsupported' };
  }

  const writer = createWriter(agent);
  if (!writer) {
    return {
      agent: agent.id,
      status: 'error',
      error: new Error(`No hook writer available for agent "${agent.id}"`),
    };
  }

  if (!writer.isApplicable()) {
    return { agent: agent.id, status: 'skipped' };
  }

  try {
    const shimCommand = agent.hooks.beforeToolUseCommand || `crewloop-shim ${agent.id}`;
    const hooks: HookEntry[] = [
      {
        event: 'PreToolUse',
        matcher: '*',
        command: shimCommand,
      },
      {
        event: 'PostToolUse',
        matcher: '*',
        command: agent.hooks.afterToolUseCommand || `crewloop-shim ${agent.id}`,
      },
      // Lifecycle events captured at the source so the dashboard receives
      // SessionStart/SessionEnd without having to infer them.
      ...(agent.hooks.lifecycleEvents || []).map((event) => ({
        event: event as AgentHookEvent,
        matcher: '*',
        command: shimCommand,
      })),
    ];

    let config = writer.readConfig();
    let needsWrite = false;

    if (!config) {
      config = writer.buildDefaultConfig(hooks);
      needsWrite = true;
    } else {
      const updated = writer.syncHooks(config, hooks);
      needsWrite = !configsEqual(config, updated);
      config = updated;
    }

    if (options.dryRun) {
      return { agent: agent.id, status: 'configured', configPath: config.path };
    }

    const backupPath = needsWrite && options.backup ? backupPathFor(config.path) : undefined;
    let backupCreated = false;

    if (backupPath && fs.existsSync(config.path)) {
      fs.copyFileSync(config.path, backupPath);
      backupCreated = true;
    }

    if (needsWrite) {
      writer.writeConfig(config);
    }

    if (agent.id === 'agy') {
      cleanupLegacyAgyConfig();
    }

    return {
      agent: agent.id,
      status: 'configured',
      configPath: config.path,
      backupPath: backupCreated ? backupPath : undefined,
    };
  } catch (error) {
    return {
      agent: agent.id,
      status: 'error',
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
}

export interface InstallHooksOptions {
  dryRun?: boolean;
  backup?: boolean;
  agents?: string[];
}

export function installHooks(options: InstallHooksOptions = {}): HookWriterResult[] {
  const { listSupportedAgents } = require('./agents');
  const agents = listSupportedAgents() as AgentConfig[];

  const filtered = options.agents?.length
    ? agents.filter((a) => options.agents!.includes(a.id))
    : agents;

  return filtered.map((agent) =>
    installHooksForAgent(agent, { dryRun: options.dryRun, backup: options.backup })
  );
}
